name: 'action'
description: 'make a lab'
inputs:
  caching: 
    description: 'input entering'
    required: false
    default: 'true'
outputs:
  coco:
    description: 'outputoo'
    value: ${{steps.so.outputs.op}}
runs: 
  using: 'composite'
  steps:
    - name: Cache dependencies
      if: inputs.caching == 'true'
      uses: actions/cache@v3
      with:
          path: ~/.npm
          key: ${{ env.CACHE_KEY }}-${{ hashFiles('**/package-lock.json') }}
    - name: Install dependencies
      run: npm ci

      shell: bash
    - name: out
      id: so
      run: echo "op='${{inputs.caching}}'">> $GITHUB_OUTPUT
      shell: bash

   